### PR TITLE
spelling: decrypter

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by slachiewicz** [comment]
this change may break other projects that do a reflection on this class.

**Comment by jsoref** [comment]
@slachiewicz: can you provide an example? I've left the old names in place with inheritance, I was hoping that'd be sufficient.

**Comment by slachiewicz** [comment]
Like here: https://www.github.com/apache/maven-ant-tasks/tree/trunk/src%2Fmain%2Fresources%2FMETA-INF%2Fplexus%2Fcomponents.xml

**Comment by jsoref** [comment]
I tried to find the schema for that file format and failed miserably.

My guess is that there's some way to write code that picks different things based on versions...

Generally fields are internal things and anyone using them is effectively acknowledging that they're breaking the rules.

That said, I'm open to input.

**Pull request closed without merging**
